manifest:
  defaults:
    revision: v0.2
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    # Forager Keyboard + Prospector
    - name: carrefinho
      url-base: https://github.com/carrefinho
    # RGB Led
    - name: caksoylar
      url-base: https://github.com/caksoylar
    # ZMK tri-state
    - name: dhruvinsh
      url-base: https://github.com/dhruvinsh
    # ZMK Dongle Screen
    - name: janpfischer
      url-base: https://github.com/janpfischer
    # HID Trackball Interface
    - name: englmaxi
      url-base: https://github.com/englmaxi
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: forager-zmk-module
      remote: carrefinho
      revision: main
    #- name: prospector-zmk-module
    #  remote: carrefinho
    #  revision: main
    - name: zmk-rgbled-widget
      remote: caksoylar
      revision: main
    - name: zmk-tri-state
      remote: dhruvinsh
      revision: main
    - name: zmk-dongle-screen
      remote: janpfischer
      revision: main
    - name: zmk-hid-trackball-interface
      remote: englmaxi
      revision: main
  self:
    path: config
